apiVersion: v1
kind: Service
metadata:
  name: order-service-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  selector:
    app: order-service
