apiVersion: v1
kind: Service
metadata:
  name: payment-service-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    app: payment-service
